### PR TITLE
Update rauc-hawkbit-updater_git.bb

### PR DESCRIPTION
**Pull request by einoj**
Update to a revision that doesn't segfault, see https://github.com/rauc/rauc-hawkbit-updater/issues/21 and https://github.com/rauc/rauc-hawkbit-updater/pull/35 

fixes: #157

Signed-off-by: Eino Juhani Oltedal <einoju@gmail.com>

### CODE REVIEW

**Review by ejoerns — CHANGES_REQUESTED** [review]
Yes, we definitely should update this!

However, I do not see any benefit in not moving to the latest revision. There are way more bug fixes in master that we would miss here. Thus please update this to match the latest master commit.

The DCO check also fails as your commit author does not match the Signed-off-by name.

**Comment by einoj** [comment]
I bumped it to the latest commit of rauc-hawkbit-updater and fixed the DCO check.

**Comment by ejoerns** [comment]
@einoj Thanks! Please squash the two commits together and rebase on top of the current master branch.

**Comment by einoj** [comment]
Rebased and squashed.

**Review by ejoerns — APPROVED** [review]
:+1:

**Comment by ejoerns** [comment]
backported to dunfell

**Pull request merged**
