### PR TITLE
rocko+rauc 0.3

### PR DESCRIPTION
**Pull request by leiflm**
The first commit adds a recipe for [rauc v0.3](https://github.com/rauc/rauc/releases/tag/v0.3).

The second commit updates the provided `_git.bb` to point to the [0.3 revision](https://github.com/rauc/rauc/commit/419387685f1e5fb0d59aa21d0eb47ddae5120600).

Even though there is no `_0.1.bb` I left the `0_0.2.bb` there for users to set `PREFERED_VERSION_rauc = 0.2` in their `distro.conf`.

### CODE REVIEW

**Comment by leiflm** [comment]
apparently the DCO-check is defect. The address doesn't match 😬

**Comment by ejoerns** [comment]
I assume this to come from the intermediate state of patches you submitted, when having @EugenWiens patches included. In PR #35 we had this issue.

**Comment by leiflm** [comment]
So how to retrigger the MR checks now targetting the right branch?

**Comment by leiflm** [comment]
ah, is it because the history contains @EugenWiens [commit](https://github.com/rauc/meta-rauc/commit/c66c82fd43eed1e0712eb9fd51fde4062426b435)?

**Comment by ejoerns** [comment]
I would assume it only checks the pull-requests history. But it was in when the check ran initially iirc.

Unsure how to retrigger it. might work by force-pushing something, otherwise we would have to ignore it.

**Comment by leiflm** [comment]
I will try to switch base branches forth and back...

**Comment by leiflm** [comment]
does not work. I'll close it and open another one...

**Comment by EugenWiens** [comment]
I'm so sorry for the trouble.

**Comment by leiflm** [comment]
@EugenWiens it's inconvenience, no trouble. @ejoerns please see #39

**Pull request closed without merging**
