### PR TITLE
add check if imgtype is set

### PR DESCRIPTION
**Pull request by EugenWiens**
in the case if the image type is not set, the behavior of the dependency can be wrong. Add fatal if the type is not set to prevent unexpected behavior.

Signed-off-by: Eugen Wiens <eugen.wiens@jumo.net>

### CODE REVIEW

**Comment by ejoerns** [comment]
Damn, seems you are right. I assumed the default to be 'image' already, but did not check it in code.

I guess to be compatible with former behavior it is best to either handle 'imgtype' `None` separately or (which i would prefer as it is more obvious) default to imgtype `'image'`

    imgtype = slotflags.get('type') if slotflags else 'image'

What do you think?

**Comment by EugenWiens** [comment]
It is fine for me. Maybe an default behavior is better.

**Comment by EugenWiens** [comment]
Should I update the pull request ?

**Comment by ejoerns** [comment]
Feel free ;)

**Pull request merged**
