### PR TITLE
make the BUNDLE_NAME and the dependent variables overridable

### PR DESCRIPTION
**Pull request by EugenWiens**
Signed-off-by: Eugen Wiens <eugen.wiens@jumo.net>
Signed-off-by: Eugen Wiens <wiens.eugens@gmail.com>

### CODE REVIEW

**Comment by EugenWiens** [comment]
I don't know what is going wrong. Sorry. Something is wrong with the signature but I don't get it.

**Comment by jluebbe** [comment]
The author needs to match the first Signed-off-by: line. I've fixed it for this branch.

**Comment by EugenWiens** [comment]
OK. Thank you @jluebbe

**Comment by ejoerns** [comment]
Thanks! Patch applied to rocko and master

**Pull request merged**
