### PR TITLE
Backports for Kirkstone

### PR DESCRIPTION
**Pull request by BenediktCyranka**
Next try to backport master to kirkstone ;)

### CODE REVIEW

**Comment by ejoerns** [comment]
Better ;)

But for consistency, the `switch to meson` commit should be added before fixing things for meson, thus maybe just before `use EXTRA_OEMESON instead of EXTRA_OECONF for setting meson opts`.

And the cherry-pick notation mentioned in #274 is still missing.

**Comment by BenediktCyranka** [comment]
Okay I will try it again.

**Comment by ejoerns** [comment]
Did you read what I wrote about force-pushes for updating the PR?

Re-Opening a new PR for each iteration is not really the intended workflow :wink:

**Comment by ejoerns** [comment]
@BenediktCyranka  Depending on your preference, I could also update this PR with the missing pieces to push the topics forward (in case edits from maintainers are enabled in your PR).

**Comment by BenediktCyranka** [comment]
@ejoerns yes editing for maintainers is now enabled. Thanks for your support.

**Comment by ejoerns** [comment]
I have reordered this now and added the cherry-pick notation.

What's missing is your Signed-off-by for the backports. Please either drop me your statement that I should add it for you (including the concreted line) here or add it by yourself. Thanks!

**Comment by ejoerns** [comment]
FTR: Updated with missing information after having received these.

**Pull request merged**
