### PR TITLE
rauc: update to 1.9

### PR DESCRIPTION
**Pull request by paletteguy**
Cherry-pick from master 1c0b05212857cc986d8788e9910bb925966a38c2

### CODE REVIEW

**Comment by ejoerns** [comment]
Please add a note that this was backported to the Signed-off history and if something was changed.
The other backport commits may serve as a blueprint.

Thanks!

**Comment by paletteguy** [comment]
Added info about backport :)

**Comment by sirhcel** [comment]
I could successfully test  dd45bd1: updating _meta-rauc_, building images, updating, and updating to the same image again worked @jluebbe.

**Comment by ejoerns** [comment]
> Added info about backport :)

`master` does not have any meaning since it is a moving target. Please have a look at the other backports and follow the pattern there noting if it is just a cherry pick or a modified version and from which exact commit it was picked, thanks!

**Comment by paletteguy** [comment]
> > Added info about backport :)
> 
> `master` does not have any meaning since it is a moving target. Please have a look at the other backports and follow the pattern there noting if it is just a cherry pick or a modified version and from which exact commit it was picked, thanks!

It's actually just a cherry-pick.

**Review by ejoerns — APPROVED** [review]
Ok, still not in the format that the other backport patches have, but since the information is sufficient, I'll accept this.

**Comment by ejoerns** [comment]
@paletteguy  Thanks for your contribution!

**Comment by jluebbe** [comment]
@paletteguy The standard message is automatically generated by `git cherry-pick -x`.

**Comment by paletteguy** [comment]
> @paletteguy The standard message is automatically generated by `git cherry-pick -x`.

Thanks very useful :)

**Pull request merged**
