### PR TITLE
added RAUC_KEYRING_FILE variable 

### PR DESCRIPTION
**Pull request by EugenWiens**
added RAUC_KEYRING_FILE variable to handle custom certificate file name instead of ca.cert.pem

### CODE REVIEW

**Comment by mnhu** [comment]
(partly) duplicate of #12 

This allows a different name, while #12 allows the CA cert to be located outside the Yocto tree. In #12, a different certificate file name can be used by setting `downloadfilename` in the SRC_URI.

**Comment by ejoerns** [comment]
In fact it does not necessarily conflict with #12. We could have a combination of both. I would suggest to merge #12 first and then rebase and adjust this one to gain something like

    RAUC_KEYRING_FILE ?= "ca.cert.pem"
    RAUC_KEYRING_URI = "file://${RAUC_KEYRING_FILE}"

    SRC_URI = "\
      ...
      ${RAUC_KEYRING_URI}
      "

**Comment by EugenWiens** [comment]
sound good

**Comment by mnhu** [comment]
Fine by me.

On June 13, 2017 9:18:35 PM GMT+02:00, Eugen Wiens <notifications@github.com> wrote:
>sound good
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/rauc/meta-rauc/pull/13#issuecomment-308220258

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by ejoerns** [comment]
Based on the changes by @mnhu I would propose this patch:

``` diff
 recipes-core/rauc/rauc-target.inc | 11 ++++++-----
 1 file changed, 6 insertions(+), 5 deletions(-)

diff --git a/recipes-core/rauc/rauc-target.inc b/recipes-core/rauc/rauc-target.inc
index 1d3ce1c..def8873 100644
--- a/recipes-core/rauc/rauc-target.inc
+++ b/recipes-core/rauc/rauc-target.inc
@@ -1,8 +1,9 @@
-RAUC_KEYRING_FILE ??= "file://ca.cert.pem"
+RAUC_KEYRING_FILE ??= "ca.cert.pem"
+RAUC_KEYRING_URI ??= "file://${RAUC_KEYRING_FILE}"

 SRC_URI_append = " \
   file://system.conf \
-  ${RAUC_KEYRING_FILE} \
+  ${RAUC_KEYRING_URI} \
   file://rauc-mark-good.service \
   "

@@ -23,11 +24,11 @@ do_install () {
         install -m 0644 ${WORKDIR}/system.conf ${D}${sysconfdir}/rauc/system.conf

         # Warn if CA file was not overwritten
-        if ! grep -q "^[^#]" ${WORKDIR}/ca.cert.pem; then
-                bbwarn "Please overwrite example ca.cert.pem with a project specific one!"
+        if ! grep -q "^[^#]" ${WORKDIR}/${RAUC_KEYRING_FILE}; then
+                bbwarn "Please overwrite example ca.cert.pem with a project specific one, or set the RAUC_KEYRING_FILE varibale with your file!"
         fi
         install -d ${D}${sysconfdir}/rauc/
-        install -m 0644 ${WORKDIR}/ca.cert.pem ${D}${sysconfdir}/rauc/
+        install -m 0644 ${WORKDIR}/${RAUC_KEYRING_FILE} ${D}${sysconfdir}/rauc/

         install -d ${D}${systemd_unitdir}/system/
         install -m 0644 ${WORKDIR}/rauc-mark-good.service ${D}${systemd_unitdir}/system/
```

@EugenWiens please also add a Signed-off-by line to your commit.

**Comment by EugenWiens** [comment]
Updated

**Pull request merged**
