### PR TITLE
rauc: add patch to skip curl service openssl certificate verification…

### PR DESCRIPTION
**Pull request by prashantdivate**
while downloading rauc bundle using REST service faced OpenSSL verification issues, So this patch will skip curl service OpenSSL certificate verification and able to download rauc bundle successfully and achieved RAUC functionality implementation for my variscite chip

NOTE: Runtime REST service application running in yocto OS build

### CODE REVIEW

**Comment by ejoerns** [comment]
A verification error is probably a sign that you should fix your SSL setup or use http instead?

**Comment by prashantdivate** [comment]
> a sign that you should fix your SSL setup

Not used http as for security purpose mandatorily I used HTTPS also no any sign used in SSL setup

**Comment by ejoerns** [comment]
@prashantdivate So probably curl does not read in your local ca-certificates correctly? What is the exact error you are facing?

**Comment by prashantdivate** [comment]
> @prashantdivate So probably curl does not read in your local ca-certificates correctly? What is the exact error you are facing?

ca-certificates used for bundle are already added in /etc/ssl/certs/ directory

root@os:/home# rauc install https://169.254.92.113:5001/Bundle.raucb
rauc-Message: installing https://169.254.92.113:5001/Bundle.raucb: installing
rauc-Message: installing https://169.254.92.113:5001/Bundle.raucb:   0% Installing
rauc-Message: installing https://169.254.92.113:5001/Bundle.raucb:   0% Determining slot states
rauc-Message: installing https://169.254.92.113:5001/Bundle.raucb:  20% Determining slot states done.
rauc-Message: installing https://169.254.92.113:5001/Bundle.raucb:  20% Checking bundle
rauc-Message: installing https://169.254.92.113:5001/Bundle.raucb:  40% Checking bundle failed.
rauc-Message: installing https://169.254.92.113:5001/Bundle.raucb: 100% Installing failed.
rauc-Message: installing https://169.254.92.113:5001/Bundle.raucb: LastError: Failed to download bundle
Installing `https://169.254.92.113:5001/Bundle.raucb` failed
2021/03/20 23:08:40 Could not update system: Could not run rauc install: exit status 1

**Comment by ejoerns** [comment]
@prashantdivate Seems as if we are not good at forwarding the high-level curl error to D-Bus here. Thus could you please provide the corresponding client log?

When using systemd, the service log should be available using `journalctl`:

    journalctl -u rauc

Also see https://rauc.readthedocs.io/en/latest/using.html#debugging-rauc for this.

**Comment by ejoerns** [comment]
FTR: Disabling `CURLOPT_SSL_VERIFYHOST` in general would not have been appropriate for meta-rauc. Doing this locally as a project-specific patch is acceptable.
Also note that patches should be submitted against the upstream project preferably.
There we have https://github.com/rauc/rauc/issues/607 which targets a very similar question.

**Pull request closed without merging**
