### PR TITLE
casync: update to latest git version (v2-267-g0efa7ab)

### PR DESCRIPTION
**Pull request by ejoerns**

### CODE REVIEW

**Comment by ejoerns** [comment]
FTR: Fixes meta-rauc master build of casync

* `master` branch was renamed to `main`
* poky master provides glibc 2.36 which casync fails building against (fixed in https://github.com/systemd/casync/commit/0efa7abffe5fffbde8c457d3c8fafbdde0bb6e4f)

**Comment by jluebbe** [comment]
I'd prefer to have that information in the commit message.

**Comment by ejoerns** [comment]
Probably worth adding, yes. (However, that it fixes the build was actually not the case when I wrote the commit message initially.)

**Review by jluebbe — APPROVED** [review]

**Comment by ejoerns** [comment]
backported to kirkstone

**Comment by ejoerns** [comment]
Backported to 'dunfell'

**Pull request merged**
