### PR TITLE
Ejo/cherrypick rhu v1.1

### PR DESCRIPTION
**Pull request by einoj**
Support for rauc-hawkbit-updater version 1.1 for dunfell

### CODE REVIEW

**Comment by ejoerns** [comment]
Thanks for the update, however, I would prefer backporting the patches instead of taking the original ones and adapting them in a follow-up commit.
I am not that happy with backporting things for another 2 years and probably we need to switch to the new override syntax here too at some point. But as long as poky doesn't I would still like to avoid breaking things for users that 'forgot' to update poky..

I also did backports explicitly by mentioning the original commit id and adding a signed-off-by for the backport so far, which I would like to keep.
As there are more things to add and, for the sake of completeness, I attempt to pick them in the order they appeared in master (if possible).

I've done this now and pushed the changes to my test branch which made it through the CI
https://github.com/ejoerns/meta-rauc/commits/dunfell

Thus if there are no objections on this, I would push this into `dunfell` branch quite soon.

**Comment by ejoerns** [comment]
Just noticed I omitted the dt-utils 2021.03 update. I've added this too now.
If CI passes again I'll gonna update 'dunfell'

**Comment by einoj** [comment]
> Thanks for the update, however, I would prefer backporting the patches instead of taking the original ones and adapting them in a follow-up commit. I am not that happy with backporting things for another 2 years and probably we need to switch to the new override syntax here too at some point. But as long as poky doesn't I would still like to avoid breaking things for users that 'forgot' to update poky..
> 
> I also did backports explicitly by mentioning the original commit id and adding a signed-off-by for the backport so far, which I would like to keep. As there are more things to add and, for the sake of completeness, I attempt to pick them in the order they appeared in master (if possible).
> 
> I've done this now and pushed the changes to my test branch which made it through the CI https://github.com/ejoerns/meta-rauc/commits/dunfell
> 
> Thus if there are no objections on this, I would push this into `dunfell` branch quite soon.

I can build your dunfell branch, so that's fine by me

**Comment by ejoerns** [comment]
Thanks for testing! CI looks fine, too. Pushed.

**Pull request closed without merging**
