### PR TITLE
README.rst: add license and CI builder badge

### PR DESCRIPTION
**Pull request by ejoerns**
Signed-off-by: Enrico Jorns <ejo@pengutronix.de>

### CODE REVIEW

**Comment by jluebbe** [comment]
Maybe also add the matrix chat badge from the RAUC readme?

**Comment by ejoerns** [comment]
Sounds like a good idea, yes. Added it.

**Comment by jluebbe** [comment]
> Sounds like a good idea, yes. Added it.

Please use the current version (I just fixed the broken link yesterday ;)

**Comment by ejoerns** [comment]
Just saw it when checking the output ;) force-pushed fixed version.

**Review by jluebbe — APPROVED** [review]

**Pull request merged**
