### PR TITLE
rauc: update to 1.6

### PR DESCRIPTION
**Pull request by ejoerns**
Signed-off-by: Enrico Jorns <ejo@pengutronix.de>

### CODE REVIEW

**Review by jluebbe — APPROVED** [review]

**Comment by ejoerns** [comment]
cherry-picked to 'hardknott' stable branch.

**Comment by mschwan-phytec** [comment]
@ejoerns Is it intentional that 1.6 only got backported to hardknott but not honister?

**Comment by ejoerns** [comment]
I've now updated the `honister` branch to include merged patch from `master`

**Comment by ejoerns** [comment]
Backported to 'dunfell'

**Pull request merged**
