### PR TITLE
Cherry pick rauc-hawkbit-updater v1.0 to dunfell

### PR DESCRIPTION
**Pull request by einoj**
Support for rauc-hawkbit-updater version 1.0 for dunfell

### CODE REVIEW

**Comment by Bastian-Krause** [comment]
Note that there is already [rauc-hawkbit-updater v1.1](https://github.com/rauc/rauc-hawkbit-updater/releases/tag/v1.1), but we do not have a meta-rauc PR for that, yet.

**Comment by einoj** [comment]
I can make a PR for rauc-hawkbit-updater v1.1 on master, then we can cherry-pick that too into dunfell.

**Comment by einoj** [comment]
Here's the PR for [v1.1,](https://github.com/rauc/meta-rauc/pull/212), let me know if I need to change the commit message.

**Comment by einoj** [comment]
I'm closing this and opening a PR for v1.1

**Pull request closed without merging**
